# NumPy: Numerical Computing

**Purpose:** Fast array operations and mathematical computations.

← [06. aiohttp](./06-aiohttp.ipynb) | [Modules](./README.md) | **07. NumPy** | [08. Pandas →](./08-pandas.ipynb)

## Simple: Arrays & Basic Operations

In [1]:
import numpy as np

# Create arrays
arr = np.array([1, 2, 3, 4, 5])
zeros = np.zeros(5)
range_arr = np.arange(0, 10, 2)

print("Array:", arr)
print("Zeros:", zeros)
print("Range:", range_arr)

Array: [1 2 3 4 5]
Zeros: [0. 0. 0. 0. 0.]
Range: [0 2 4 6 8]


In [2]:
# Operations
print("arr * 2:", arr * 2)
print("arr + arr:", arr + arr)
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Std:", np.std(arr))

arr * 2: [ 2  4  6  8 10]
arr + arr: [ 2  4  6  8 10]
Sum: 15
Mean: 3.0
Std: 1.4142135623730951


## Medium: Matrices & Linear Algebra

In [3]:
import numpy as np

# 2D arrays
matrix = np.array([[1, 2], [3, 4]])
print("Matrix shape:", matrix.shape)
print("Matrix:\n", matrix)

Matrix shape: (2, 2)
Matrix:
 [[1 2]
 [3 4]]


In [4]:
# Matrix operations
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix, matrix2)
print("Matrix multiplication:\n", result)

Matrix multiplication:
 [[19 22]
 [43 50]]


In [5]:
# Statistics
data = np.array([1, 2, 3, 4, 5])
print("Std:", np.std(data))
print("75th percentile:", np.percentile(data, 75))

Std: 1.4142135623730951
75th percentile: 4.0


## Complex: Broadcasting & Vectorization

In [6]:
import numpy as np

# Broadcasting
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
result = a + b
print("Broadcasting result shape:", result.shape)
print(result)

Broadcasting result shape: (3, 3)
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [7]:
# Vectorized operations
x = np.linspace(0, 2*np.pi, 10)
y = np.sin(x)
print("Sin values:", y)

Sin values: [ 0.00000000e+00  6.42787610e-01  9.84807753e-01  8.66025404e-01
  3.42020143e-01 -3.42020143e-01 -8.66025404e-01 -9.84807753e-01
 -6.42787610e-01 -2.44929360e-16]


In [8]:
# Advanced indexing
arr = np.arange(20).reshape(4, 5)
mask = arr > 10
filtered = arr[mask]
print("Values > 10:", filtered)

Values > 10: [11 12 13 14 15 16 17 18 19]


---

**Install:** `pip install numpy` | **Use:** Data science, ML preprocessing, scientific computing

← [06. aiohttp](./06-aiohttp.ipynb) | [Modules](./README.md) | **07. NumPy** | [08. Pandas →](./08-pandas.ipynb)

## Resources

- [NumPy Documentation](https://numpy.org/doc/)
- [NumPy User Guide](https://numpy.org/doc/stable/user/)
